### ISSUE TITLE
What about using mqtt?

### ISSUE THREAD

**Issue by syphernl** [ltoinel/domogeeek#1]
Hi Ludovic!

Before I stumbled upon this project I was working on writing [my own](https://github.com/syphernl/mqtt-openzwave) system. Since both have a very similar approach (loosely coupled) I might as well use this one instead. :-)

However, I was planning on running the system externally and only with the "hardware" part (ZWave bridge) locally. This allows greater flexibility and security since the "brain" is hosted in a more secure environment.

For this I came across MQTT which is pretty easy to work with. For the webinterface I'm planning to use AngularJS and Websockets for realtime execution of actions and display of information (temperatures, light states etc).

An added bonus of MQTT is that you can use any system that can talk to MQTT to write code in so not all parts must be nodeJS. For presence for instance it could be linked to [ownTracks](http://owntracks.org/) which uses MQTT as well.

Perhaps we should work together on this :-)

**Comment by ltoinel** [comment]
Excellent ideas !
I didn't know MQTT, this seems to be a standard for IoT communication.

Advantages : 
- More interoperability between the process and external applications
- Real time websocket communication with the frontend

Disadvantages : 
- The listener services must be statefull 

I took a look to your code, the MQTT integration of the OpenZwave NodeJS wrapper should be easy to do.

What MQTT server are you using ? Mosca ?

**Comment by syphernl** [comment]
My code wasn't doing much MQTT at the moment other than logging to test. I still had to think of a proper way of dealing with actions and data collection with ZWave.

I'm currently using [mosquitto](http://mosquitto.org/), but Mosca looks nice too. 
Your apps already use MongoDB so it probably makes sense to use that one instead.

**Comment by ltoinel** [comment]
Did you take a look to : https://github.com/eclipse/ponte ?

**Comment by ltoinel** [comment]
I started a new branch with a new structure : 
- app.js at the root is an adapted MQTT / REST / COAP server
- all the elements in "apps" will be connected to the MQTT server using pubsub.

**Comment by syphernl** [comment]
I haven't heard of Ponte but it does look nice!

**Comment by ltoinel** [comment]
The Multipush module has been rewriting over an MQTT broker. It's sexy !
Next step : Test the Zwave with my MQTT adaptation

**Comment by ltoinel** [comment]
Finishing the MQQT adaptation, next step : testing, then web administration

**Comment by syphernl** [comment]
Nice to see you're making progress with this!
