### ISSUE TITLE
node-red integration / if-then-else

### ISSUE THREAD

**Issue by syphernl** [ltoinel/domogeeek#3]
Perhaps its nice if this could have integration with [Node-RED](http://nodered.org/) for "if-then-else" actions. I haven't used it yet (other than checking if it runs and dragging some stuff around) but it could be a nice addition.

IIUC this app should be able to deal with the whole "if-then-else" handling for making complex plans such as:
- If the sun has gone down;
- Turn on the lights in the living room
- Close the curtains

Or
- Motion is detected in the hallway;
- And if the alarm is armed (alarm could be a simple nodejs app);
- And if the trusted devices (phones) are out of range;
- Send out alarms to SMS & PushBullet;
- Trigger the ZWave alarm;

**Comment by ltoinel** [comment]
I didn't know Node-red, it looks very great and usefull to create workflows.
Did you take a look to the "Zwave" connector in Node-Red  ?

**Comment by syphernl** [comment]
Yes, this is based on OpenZWave but I haven't tested that part yet. At the moment all I have is a ZWave stick and Fibaro Binary Sensor which I haven't yet been able to get to work.
